/** The score as data: lengths, tempi, exit points and gains for every file the engine plays.
 * Generated by appenc.py from the rendered kit. Do not edit by hand. */
export const SCORE = {
 "version": "1.0",
 "preroll": 0.1,
 "roles": [
  "floor",
  "wind_soft",
  "wind_full",
  "home",
  "car",
  "bakery",
  "battery",
  "cable",
  "thread"
 ],
 "scenes": {
  "wind": {
   "title": "Awakening",
   "len": 32.0,
   "bars": 8,
   "bpm": 60,
   "exitBars": 2,
   "stageLufs": -30.5,
   "stems": {
    "floor": {
     "norm": 25.84,
     "depth": 0.49
    },
    "wind_soft": {
     "norm": 24.6,
     "depth": 0.275
    },
    "wind_full": {
     "norm": 22.87,
     "depth": 0.225
    },
    "home": {
     "norm": 28.01,
     "depth": 0.65
    },
    "car": {
     "norm": 22.93,
     "depth": 0.3
    },
    "bakery": {
     "norm": 23.77,
     "depth": 0.79
    },
    "battery": {
     "norm": 29.2,
     "depth": 0.625
    },
    "cable": {
     "norm": 33.47,
     "depth": 0.9
    },
    "thread": {
     "norm": 21.42,
     "depth": 0.5
    }
   }
  },
  "day": {
   "title": "Possibility",
   "len": 35.5556,
   "bars": 16,
   "bpm": 108,
   "exitBars": 4,
   "stageLufs": -27.2,
   "stems": {
    "floor": {
     "norm": 22.32,
     "depth": 0.49
    },
    "wind_soft": {
     "norm": 20.04,
     "depth": 0.275
    },
    "wind_full": {
     "norm": 17.88,
     "depth": 0.225
    },
    "home": {
     "norm": 24.05,
     "depth": 0.65
    },
    "car": {
     "norm": 21.21,
     "depth": 0.3
    },
    "bakery": {
     "norm": 23.65,
     "depth": 0.79
    },
    "battery": {
     "norm": 26.6,
     "depth": 0.4
    },
    "cable": {
     "norm": 34.69,
     "depth": 0.9
    },
    "thread": {
     "norm": 15.85,
     "depth": 0.367
    }
   }
  },
  "dawn": {
   "title": "Gathering",
   "len": 25.2632,
   "bars": 8,
   "bpm": 76,
   "exitBars": 1,
   "stageLufs": -30.0,
   "stems": {
    "floor": {
     "norm": 22.68,
     "depth": 0.49
    },
    "wind_soft": {
     "norm": 25.39,
     "depth": 0.275
    },
    "wind_full": {
     "norm": 20.96,
     "depth": 0.225
    },
    "home": {
     "norm": 25.4,
     "depth": 0.65
    },
    "car": {
     "norm": 23.16,
     "depth": 0.3
    },
    "bakery": {
     "norm": 27.98,
     "depth": 0.79
    },
    "battery": {
     "norm": 26.79,
     "depth": 0.4
    },
    "cable": {
     "norm": 36.01,
     "depth": 0.9
    },
    "thread": {
     "norm": 22.53,
     "depth": 0.5
    }
   }
  },
  "peak": {
   "title": "Choice",
   "len": 34.2857,
   "bars": 8,
   "bpm": 56,
   "exitBars": 2,
   "stageLufs": -29.6,
   "stems": {
    "floor": {
     "norm": 22.93,
     "depth": 0.49
    },
    "wind_soft": {
     "norm": 25.0,
     "depth": 0.275
    },
    "wind_full": {
     "norm": 21.22,
     "depth": 0.225
    },
    "home": {
     "norm": 28.1,
     "depth": 0.65
    },
    "car": {
     "norm": 27.12,
     "depth": 0.3
    },
    "bakery": {
     "norm": 23.17,
     "depth": 0.79
    },
    "battery": {
     "norm": 27.34,
     "depth": 0.4
    },
    "cable": {
     "norm": 33.54,
     "depth": 0.9
    },
    "thread": {
     "norm": 20.3,
     "depth": 0.3
    }
   }
  }
 },
 "beds": {
  "question": {
   "len": 5.9144,
   "file": 14.01,
   "norm": 9.13,
   "gainDb": 6.0,
   "lufs": -28.6
  },
  "ride": {
   "len": 7.5177,
   "file": 15.57,
   "norm": 4.34,
   "gainDb": 0.0,
   "lufs": -19.6
  },
  "release": {
   "len": 48.413,
   "file": 58.51,
   "norm": 0.0,
   "gainDb": 0.0,
   "lufs": -15.2
  },
  "release_brief": {
   "len": 14.1775,
   "file": 22.28,
   "norm": 0.32,
   "gainDb": 0.0,
   "lufs": -15.0
  },
  "afterglow": {
   "len": 38.4762,
   "file": 38.78,
   "norm": 21.59,
   "gainDb": 7.0,
   "lufs": -36.8
  }
 },
 "shots": {
  "call_wind": {
   "role": "wind_full",
   "len": 2.5,
   "file": 2.86,
   "norm": 20.3,
   "depth": 0.225,
   "gainDb": 14.3
  },
  "call_wind_2": {
   "role": "wind_full",
   "len": 2.5,
   "file": 2.86,
   "norm": 21.16,
   "depth": 0.225,
   "gainDb": 15.2
  },
  "call_home": {
   "role": "home",
   "len": 2.5,
   "file": 3.02,
   "norm": 21.69,
   "depth": 0.72,
   "gainDb": 15.7
  },
  "call_home_2": {
   "role": "home",
   "len": 2.5,
   "file": 3.03,
   "norm": 30.25,
   "depth": 0.58,
   "gainDb": 22.0
  },
  "call_car": {
   "role": "car",
   "len": 2.0,
   "file": 2.63,
   "norm": 22.96,
   "depth": 0.3,
   "gainDb": 17.0
  },
  "call_car_2": {
   "role": "car",
   "len": 2.0,
   "file": 3.09,
   "norm": 20.94,
   "depth": 0.3,
   "gainDb": 14.9
  },
  "call_bakery": {
   "role": "bakery",
   "len": 2.5,
   "file": 2.72,
   "norm": 25.01,
   "depth": 0.78,
   "gainDb": 19.0
  },
  "call_bakery_2": {
   "role": "bakery",
   "len": 2.5,
   "file": 2.71,
   "norm": 24.21,
   "depth": 0.78,
   "gainDb": 18.2
  },
  "call_battery": {
   "role": "battery",
   "len": 2.0,
   "file": 6.01,
   "norm": 22.87,
   "depth": 0.625,
   "gainDb": 16.9
  },
  "call_battery_2": {
   "role": "battery",
   "len": 2.0,
   "file": 6.43,
   "norm": 24.02,
   "depth": 0.4,
   "gainDb": 18.0
  },
  "call_cable": {
   "role": "cable",
   "len": 2.0,
   "file": 3.99,
   "norm": 26.44,
   "depth": 0.9,
   "gainDb": 20.4
  },
  "sting_decision": {
   "role": "battery",
   "len": 1.5,
   "file": 3.49,
   "norm": 27.8,
   "depth": 0.625,
   "gainDb": 21.8
  },
  "sting_ask": {
   "role": "thread",
   "len": 1.5,
   "file": 1.97,
   "norm": 23.2,
   "depth": 0.5,
   "gainDb": 17.2
  },
  "sting_conflict": {
   "role": "wind_soft",
   "len": 2.5,
   "file": 3.15,
   "norm": 23.2,
   "depth": 0.275,
   "gainDb": 17.2
  },
  "sting_commit": {
   "role": "battery",
   "len": 3.5,
   "file": 8.1,
   "norm": 19.13,
   "depth": 0.718,
   "gainDb": 13.1
  },
  "gliss_up": {
   "role": "battery",
   "len": 1.5,
   "file": 6.55,
   "norm": 20.41,
   "depth": 0.4,
   "gainDb": 14.4
  },
  "gliss_down": {
   "role": "battery",
   "len": 1.5,
   "file": 6.55,
   "norm": 23.35,
   "depth": 0.4,
   "gainDb": 17.3
  },
  "timp_soft": {
   "role": "cable",
   "len": 1.5,
   "file": 2.19,
   "norm": 27.54,
   "depth": 0.9,
   "gainDb": 21.5
  },
  "timp_hard": {
   "role": "cable",
   "len": 2.0,
   "file": 4.77,
   "norm": 13.25,
   "depth": 0.9,
   "gainDb": 7.3
  }
 },
 "hall": {
  "fileGain": 4.1584,
  "predelay": 0.024,
  "sendDb0": -13.0,
  "sendDbPerDepth": 7.0,
  "sourceToSend": 0.884
 }
};
